### ISSUE TITLE
Missing link for October 1, 2023

### ISSUE THREAD

**Issue by craftersshaft** [MrSujano/Sources#1]
The sources for October 1, 2023 did not include the article about colorizing Game Boy games, which can be found here:
https://toruzz.com/blog/how-to-colorize-gb-games-first-steps/
The specific part mentioned in the video:
https://toruzz.com/blog/how-to-colorize-gb-games-02

**Comment by MrSujano** [comment]
Great spot! Appreciate that!

The link has been added 🙂

Oct 1, 2023 9:06:36 p.m. craftersshaft ***@***.***>:

**Comment by craftersshaft** [comment]
Thank you so much, love hearing about news in emulation and other gaming tech!
