### ISSUE TITLE
Releases page doesn't contain the latest release

### ISSUE THREAD

**Issue by psande** [MrSujano/Sources#2]
Hi! 

First, thanks for your daily videos! You mix the right amount of emulation, linux and tech in a nice format!

Besides watching your videos, I use RSS on the release page to follow you.

https://github.com/MrSujano/Sources/releases

Currently, not sure why, the releases are not in order. I think it might because of the US format date, but not sure.

**Comment by MrSujano** [comment]
You'd be correct with the date format - that appears to be throwing things off. Moving forward I'll be using YYYY.MM.DD.
To fix the overall order, I'll have to go through each of my old YT videos to change the description of each one which will take time. 

Thanks for the spot on this one. I'll eventually get around to fixing the old ones, but it might be awhile.

**Comment by psande** [comment]
Thanks a lot of fixing it! And again, thanks for your videos!

**Comment by psande** [comment]
Thanks a lot of fixing it! And again, thanks for your videos!
